version: '3.7'

services:
  eulennest:
    container_name: eulennest
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        img_pwd: ${IMG_PWD}
    # ports:
    #   - '3000:80'
    # environment:
    #  - VIRTUAL_HOST=foerderverein-eulennest.de
    #  - LETSENCRYPT_HOST=foerderverein-eulennest.de
    # #  - VIRTUAL_PORT=3000
    #  - LETSENCRYPT_EMAIL=martin.plank@protonmail.com
    
